version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d 
    ports: ['5433:5432']

  pgadmin:
    image: dpage/pgadmin4
    container_name: padmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db  

  redis:
    image: redis:7
    ports: ['6379:6379']

  backend:
    build: ./backend
    env_file: ./backend/.env.example
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/finance
      - JWT_SECRET=supersecret_jwt_key
      - REDIS_HOST=redis
    ports: ['4000:4000']
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports: ['3000:80']
    depends_on:
      - backend

volumes:
  db-data:
